# Generated by Django 2.1.3 on 2019-01-10 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('logo', models.ImageField(default='', upload_to='img/logo', verbose_name='logo')),
                ('newprice', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='新车价格')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_data', models.DateField(verbose_name='上牌日期')),
                ('engineNo', models.CharField(max_length=50, verbose_name='发动机号')),
                ('mileage', models.IntegerField(verbose_name='公里数')),
                ('record', models.CharField(max_length=200, verbose_name='维修记录')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='期望成功价格')),
                ('picture', models.ImageField(upload_to='img/car', verbose_name='汽车图片')),
                ('formalities', models.BooleanField(default=True, verbose_name='手续是否齐全')),
                ('debt', models.BooleanField(default=False, verbose_name='是否有债务')),
                ('promise', models.TextField(null=True, verbose_name='卖家承诺')),
                ('status', models.IntegerField(choices=[(0, '审核中'), (1, '已审核'), (2, '未审核'), (3, '未通过')], default=2, verbose_name='审核状态')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
